"""Initial migration: create all tables

Revision ID: 52c1001068a0
Revises: 
Create Date: 2026-02-26 10:23:04.063580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c1001068a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdpa_accepted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('admin_remark',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('manual_attendance_requests', schema=None) as batch_op:
        batch_op.alter_column('admin_remark',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('ot_requests', schema=None) as batch_op:
        batch_op.alter_column('admin_remark',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('payroll_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_deduction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('early_deduction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('calc_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('calc_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_details', schema=None) as batch_op:
        batch_op.drop_column('calc_end_date')
        batch_op.drop_column('calc_start_date')
        batch_op.drop_column('status')
        batch_op.drop_column('early_deduction')
        batch_op.drop_column('late_deduction')

    with op.batch_alter_table('ot_requests', schema=None) as batch_op:
        batch_op.alter_column('admin_remark',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('manual_attendance_requests', schema=None) as batch_op:
        batch_op.alter_column('admin_remark',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.alter_column('admin_remark',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('pdpa_accepted')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
