"""add benefits

Revision ID: 75d6e309b4f5
Revises: 52c1001068a0
Create Date: 2026-03-19 22:00:23.700425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '75d6e309b4f5'
down_revision: Union[str, Sequence[str], None] = '52c1001068a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('benefits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benefits_id'), ['id'], unique=False)

    op.create_table('employee_benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefits.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'benefit_id', name='uq_employee_benefit')
    )
    with op.batch_alter_table('employee_benefits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_benefits_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_benefits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_benefits_id'))

    op.drop_table('employee_benefits')
    with op.batch_alter_table('benefits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benefits_id'))

    op.drop_table('benefits')
    # ### end Alembic commands ###
