"""benefit transaction approval workflow

Revision ID: eca1c4622abc
Revises: 9b1c2d3e4f5
Create Date: 2026-03-20 08:27:32.713874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'eca1c4622abc'
down_revision: Union[str, Sequence[str], None] = '9b1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_cols = {col['name'] for col in inspector.get_columns('benefit_transactions')}
    existing_fks = {fk.get('name') for fk in inspector.get_foreign_keys('benefit_transactions')}
    fk_name = 'fk_benefit_transactions_approved_by_id'

    with op.batch_alter_table('benefit_transactions', schema=None) as batch_op:
        if 'used_at' not in existing_cols:
            batch_op.add_column(sa.Column('used_at', sa.DateTime(), nullable=True))
        if 'requested_at' not in existing_cols:
            batch_op.add_column(sa.Column('requested_at', sa.DateTime(), nullable=True))
        if 'status' not in existing_cols:
            batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        if 'admin_remark' not in existing_cols:
            batch_op.add_column(sa.Column('admin_remark', sa.String(), nullable=True))
        if 'approved_by_id' not in existing_cols:
            batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        if 'approved_at' not in existing_cols:
            batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        if fk_name not in existing_fks:
            batch_op.create_foreign_key(fk_name, 'employees', ['approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_cols = {col['name'] for col in inspector.get_columns('benefit_transactions')}
    fk_name = 'fk_benefit_transactions_approved_by_id'

    with op.batch_alter_table('benefit_transactions', schema=None) as batch_op:
        # Drop FK first if exists
        fks = {fk.get('name') for fk in inspector.get_foreign_keys('benefit_transactions')}
        if fk_name in fks:
            batch_op.drop_constraint(fk_name, type_='foreignkey')
        if 'approved_at' in existing_cols:
            batch_op.drop_column('approved_at')
        if 'approved_by_id' in existing_cols:
            batch_op.drop_column('approved_by_id')
        if 'admin_remark' in existing_cols:
            batch_op.drop_column('admin_remark')
        if 'status' in existing_cols:
            batch_op.drop_column('status')
        if 'requested_at' in existing_cols:
            batch_op.drop_column('requested_at')
        if 'used_at' in existing_cols:
            batch_op.drop_column('used_at')

    # ### end Alembic commands ###
