# ruff: noqa: F601
TRANSLATIONS = {
    "th": {
        # --- Navbar ---
        "nav_emp": "พนักงาน",
        "nav_emp_list": "รายชื่อพนักงาน",
        "nav_add_emp": "เพิ่มพนักงาน",
        "nav_broadcast": "ส่งประกาศข่าวสาร",
        "nav_time_mgmt": "การจัดการเวลา",
        "nav_set_schedule": "กำหนดตารางเวลา",
        "nav_check_leaves": "ตรวจสอบการลา",
        "nav_approve_manual": "อนุมัติเวลา (Manual)",
        "nav_holidays": "วันหยุดนักขัตฤกษ์",
        "nav_leave_summary": "สรุปการลาพนักงาน",
        "nav_attendance_report": "รายงานการลงเวลาทั้งหมด",
        "nav_record_time": "บันทึกเวลา/ลา",
        "nav_header_personal": "ลงเวลา & ข้อมูลส่วนตัว",
        "nav_checkin": "ลงเวลาทำงาน (Check-in)",
        "nav_forgot_time": "แจ้งลืมลงเวลา",
        "nav_my_attendance": "ประวัติการลงเวลาของฉัน",
        "nav_header_leave": "การลาพักผ่อน",
        "nav_apply_leave": "ยื่นใบลา",
        "nav_my_leaves": "ประวัติการลาของฉัน",
        "nav_payroll_ot": "Payroll & OT",
        "nav_header_admin_payroll": "การจัดการเงินเดือน (Admin)",
        "nav_calc_payroll": "คำนวณเงินเดือน",
        "nav_payroll_summary": "รายงานเงินเดือน",
        "nav_tax_sso": "รายงาน SSO และ ภาษี",
        "nav_approve_ot": "อนุมัติโอที",
        "nav_header_staff": "สำหรับพนักงาน",
        "nav_payslip": "ใบแจ้งเงินเดือน (Payslip)",
        "nav_req_ot": "ขอโอที",
        "nav_my_ot": "ประวัติโอทีของฉัน",
        "nav_hello": "สวัสดี",
        "nav_my_profile": "ข้อมูลส่วนตัว",
        "nav_change_pw": "เปลี่ยนรหัสผ่าน",
        "nav_header_sys_settings": "ตั้งค่าระบบ",
        "nav_payroll_formula": "สูตรคำนวณเงินเดือน",
        "nav_org_settings": "ตั้งค่าองค์กร & โลโก้",
        "nav_logout": "ออกจากระบบ",

        # --- Dashboard Page ---
        "employees_list": "รายชื่อบุคลากรทั้งหมด",
        "add_employee": "เพิ่มพนักงานใหม่",
        "save_success": "บันทึกสำเร็จ!",
        "update_success": "อัปเดตข้อมูลสำเร็จ!",
        "delete_success": "ลบข้อมูลพนักงานแล้ว",
        "photo": "รูป",
        "employee_code": "รหัสพนักงาน",
        "full_name": "ชื่อ-นามสกุล",
        "position": "ตำแหน่ง",
        "phone": "เบอร์โทรศัพท์",
        "role": "สิทธิใช้งาน",
        "manage": "จัดการ",
        "view_info": "ดูข้อมูล",
        "edit": "แก้ไข",
        "manage_quota": "จัดการโควตา",
        "delete": "ลบ",
        "confirm_delete": "ยืนยันการลบรายชื่อพนักงานท่านนี้?",
        "employee_details": "รายละเอียดบุคลากร",
        "close": "ปิดหน้าต่าง",
        "loading_error": "เกิดข้อผิดพลาดในการโหลดข้อมูล",

        # --- Add Employee Page (ใหม่!) ---
        "add_emp_title": "เพิ่มข้อมูลบุคลากรใหม่",
        "emp_code": "รหัสพนักงาน",
        "first_name": "ชื่อ",
        "last_name": "นามสกุล",
        "nickname": "ชื่อเล่น",
        "id_card": "เลขบัตรประชาชน",
        "pos_dept": "ตำแหน่ง/แผนก",
        "set_password": "กำหนดรหัสผ่านเข้าใช้งาน *",
        "pw_placeholder": "อย่างน้อย 4 ตัวอักษร",
        "address": "ที่อยู่ตามทะเบียนบ้าน",
        "base_salary": "ฐานเงินเดือน",
        "pos_allowance": "ค่าตำแหน่ง",
        "bank_acc": "หมายเลขบัญชีธนาคาร",
        "system_role": "สิทธิการใช้งานระบบ",
        "profile_pic": "รูปถ่ายพนักงาน (JPG/PNG)",
        "docs": "เอกสารสมัครงาน (หลายไฟล์ PDF)",
        "sick_quota": "โควตาลาป่วย (วัน)",
        "personal_quota": "โควตาลากิจ (วัน)",
        "vacation_quota": "โควตาพักร้อน (วัน)",
        "cancel": "ยกเลิก",
        "reset": "ล้างข้อมูล",
        "save_emp": "บันทึกข้อมูลพนักงาน",
        "doctor": "แพทย์",
        "nurse": "ผู้ช่วยทันตแพทย์",
        "staff": "เจ้าหน้าที่",

        # --- Edit Employee Page ---
        "edit_emp_title": "แก้ไขข้อมูลบุคลากร",
        "change_profile_pic": "เปลี่ยนรูปถ่ายพนักงาน (ถ้าต้องการ)",
        "add_docs": "เพิ่มเอกสาร PDF (ถ้าต้องการ)",
        "set_leave_quota": "กำหนดสิทธิการลาต่อปี (จำนวนวัน)",
        "save_changes": "บันทึกการแก้ไขทั้งหมด",
        "back": "ย้อนกลับ",

        # --- Import Attendance Page ---
        "import_att_title": "นำเข้าข้อมูลการลงเวลา (Excel)",
        "import_att_format_header": "รูปแบบไฟล์ที่รองรับ:",
        "import_att_format_desc": "ไฟล์ต้องมีหัวคอลัมน์ดังนี้",
        "import_att_columns": "เลือกไฟล์ Excel (.xlsx)",
        "import_att_btn": "เริ่มนำเข้าข้อมูลเข้าสู่ระบบ",

        # --- OT Approval Page ---
        "ot_approval_title": "อนุมัติการทำงานล่วงเวลา (OT)",
        "emp_id": "รหัสพนักงาน",
        "request_date": "วันที่ขอ",
        "time_range": "ช่วงเวลา",
        "total_minutes": "รวมนาที",
        "ot_type": "ประเภท OT",
        "reason": "เหตุผล",
        "minute_unit": "น.",
        "placeholder_remark": "ระบุเหตุผล (ถ้ามี)",
        "approve": "อนุมัติ",
        "reject": "ปฏิเสธ",
        "confirm_reject": "ยืนยันการปฏิเสธ?",
        "no_pending_ot": "ไม่มีคำขอ OT ที่รอการอนุมัติ",
        # --- Broadcast Page ---
        "broadcast_title": "ส่งประกาศแจ้งพนักงานทุกคน",
        "broadcast_subject": "หัวข้อประกาศ",
        "broadcast_placeholder_title": "เช่น แจ้งปิดทำการล่วงหน้า",
        "broadcast_message": "ข้อความที่ต้องการแจ้ง",
        "broadcast_placeholder_msg": "ระบุรายละเอียดที่พนักงานควรทราบ...",
        "broadcast_info": "ข้อความนี้จะเด้งบนหน้าจอล็อก (Lock Screen) ของพนักงานทุกคนที่กดรับแจ้งเตือนไว้",
        "broadcast_btn": "ส่งประกาศทันที",
        "broadcast_confirm": "ยืนยันการส่งประกาศหาพนักงานทุกคนหรือไม่?",
        # --- Schedule Page ---
        "sch_title": "กำหนดตารางเวลาและวันหยุดรายบุคคล",
        "sch_emp": "พนักงาน",
        "sch_check_in": "เข้างาน",
        "sch_check_out": "เลิกงาน",
        "sch_time": "เวลา",
        "sch_late_min": "สายได้ (นาที)",
        "sch_early_min": "ออกก่อน (นาที)",
        "sch_work_days": "วันทำงาน (ติ๊กเลือกเพื่อกำหนดวันทำงาน)",
        "sch_guide_title": "คำแนะนำในการตั้งค่า",
        "sch_guide_1": "วันทำงาน: วันที่ติ๊กเครื่องหมาย = วันทำงาน | ว่างไว้ = วันหยุดประจำสัปดาห์",
        "sch_guide_2": "การคำนวณสถานะ: ระบบจะเช็ค 'ขาดงาน' เฉพาะในวันที่ระบุเป็นวันทำงาน",
        "sch_guide_3": "ผลกระทบ: ช่วยให้จัดการพนักงานที่สลับกะได้แม่นยำ",
        "sch_save_btn": "บันทึกตารางเวลาทั้งหมด",
        # วันย่อ
        "day_mon": "จ", "day_tue": "อ", "day_wed": "พ", "day_thu": "พฤ", 
        "day_fri": "ศ", "day_sat": "ส", "day_sun": "อา",
        # --- Leave Approval Page ---
        "leave_list_title": "รายการคำขอลาหยุด",
        "leave_submit_date": "วันที่ยื่น",
        "leave_emp_name": "พนักงาน",
        "leave_type_label": "ประเภท",
        "leave_date_range": "วันที่ลา",
        "leave_reason": "เหตุผลการลา",
        "leave_evidence": "หลักฐาน",
        "leave_status": "สถานะ",
        "leave_manage": "จัดการ/เหตุผลปฏิเสธ",
        "leave_view_file": "ดูไฟล์",
        "leave_no_file": "ไม่มี",
        "leave_pending": "รออนุมัติ",
        "leave_approved": "อนุมัติแล้ว",
        "leave_rejected": "ปฏิเสธ",
        "leave_reason_header": "เหตุผล",
        "leave_approve_btn": "อนุมัติ",
        "leave_reject_btn": "ปฏิเสธ",
        "leave_confirm_reject": "ยืนยันการปฏิเสธใบลา?",
        "leave_no_data": "ยังไม่มีรายการคำขอลาในขณะนี้",
        "leave_managed_at": "จัดการเมื่อ",
        "leave_remark_placeholder": "เหตุผล (ใส่เฉพาะตอนปฏิเสธก็ได้)",
        # --- Attendance Requests Page ---
        "att_mgmt_title": "จัดการคำขอลงเวลาทำงาน",
        "att_approve_all": "อนุมัติทั้งหมด",
        "att_import_excel": "นำเข้าจาก Excel",
        "att_import_title": "นำเข้าข้อมูลการลงเวลา",
        "att_import_template_msg": "โปรดใช้ไฟล์แม่แบบเพื่อให้ข้อมูลถูกต้อง 100%",
        "att_download_template": "ดาวน์โหลดไฟล์แม่แบบ Excel",
        "att_select_file": "เลือกไฟล์ (.xlsx, .csv)",
        "att_start_import": "เริ่มนำเข้าข้อมูล",
        "att_col_req_date": "วันที่ยื่นคำขอ",
        "att_col_emp": "พนักงาน",
        "att_col_att_date": "วันที่ลงเวลา",
        "att_col_time": "เวลา (เข้า/ออก)",
        "att_col_reason": "เหตุผล / หมายเหตุ",
        "att_col_location": "ตำแหน่ง",
        "att_col_actions": "ดำเนินการ",
        "att_no_pending": "ไม่พบคำขอที่รอการอนุมัติ",
        "att_confirm_approve_all": "ยืนยันอนุมัติคำขอที่ค้างอยู่ทั้งหมดหรือไม่?",
        "att_confirm_approve": "ยืนยันการอนุมัติ?",
        "att_confirm_reject": "ยืนยันการปฏิเสธ?",
        # --- Holidays Page ---
        "hld_title": "จัดการวันหยุดนักขัตฤกษ์",
        "hld_label_date": "วันที่หยุด",
        "hld_label_name": "ชื่อวันหยุด",
        "hld_placeholder_name": "เช่น วันแรงงาน, วันสงกรานต์",
        "hld_btn_save": "บันทึกวันหยุด",
        "hld_col_date": "วันที่",
        "hld_col_name": "ชื่อวันหยุด",
        "hld_col_manage": "จัดการ",
        "hld_btn_delete": "ลบ",
        "hld_no_data": "ยังไม่ได้กำหนดวันหยุดนักขัตฤกษ์",
        "hld_confirm_delete": "ยืนยันการลบวันหยุดนี้?",
        # --- Leave Summary Page ---
        "ls_title": "สรุปโควตาและการลาพนักงาน",
        "ls_print_btn": "พิมพ์รายงาน",
        "ls_col_emp": "พนักงาน",
        "ls_col_sick": "ลาป่วย (คงเหลือ/โควตา)",
        "ls_col_personal": "ลากิจ (คงเหลือ/โควตา)",
        "ls_col_vacation": "พักร้อน (คงเหลือ/โควตา)",
        "ls_col_status": "สถานะ",
        "ls_unit_day": "วัน",
        "ls_status_active": "กำลังทำงาน",
        "ls_status_inactive": "ลาออก/ระงับ",
        "ls_id_label": "รหัส",
        # --- Attendance Report Page ---
        "rep_title": "รายงานสรุปการลงเวลาทำงาน",
        "rep_from": "จากวันที่",
        "rep_to": "ถึงวันที่",
        "rep_search_label": "ค้นหาพนักงาน (ชื่อ หรือ รหัส)",
        "rep_search_placeholder": "ระบุชื่อ หรือ รหัสพนักงาน...",
        "rep_btn_search": "ค้นหา",
        "rep_btn_export": "Export Excel",
        "rep_period_label": "รายงานช่วงวันที่:",
        "rep_to_label": "ถึง",
        "rep_col_date": "วันที่",
        "rep_col_code": "รหัสพนักงาน",
        "rep_col_name": "ชื่อ-นามสกุล",
        "rep_col_in": "เวลาเข้า",
        "rep_col_late": "สาย (นาที)",
        "rep_col_out": "เวลาออก",
        "rep_col_early": "ออกก่อน (นาที)",
        "rep_col_status": "สถานะ",
        "rep_col_photo": "รูปถ่าย",
        "rep_col_gps": "พิกัด (GPS)",
        "rep_status_normal": "ปกติ",
        "rep_status_absent": "ขาดงาน",
        "rep_status_late": "สาย",
        "rep_status_abnormal": "ผิดปกติ",
        "rep_status_holiday": "วันหยุด",
        "rep_photo_in": "เข้า",
        "rep_photo_out": "ออก",
        "rep_map_btn": "แผนที่",
        "rep_no_gps": "ไม่มีพิกัด",
        "rep_no_data": "ไม่พบข้อมูลการลงเวลาในช่วงวันที่เลือก",
        "rep_modal_title": "รูปถ่ายยืนยันตัวตน",
        "rep_photo_title_in": "รูปตอนเข้างาน",
        "rep_photo_title_out": "รูปตอนออกงาน",
        "rep_print_btn": "พิมพ์รายงาน",
        # --- Attendance Page ---
        "att_page_title": "ระบบลงเวลาเข้า-ออกงาน (ยืนยันตัวตนด้วยภาพถ่าย)",
        "att_btn_checkin": "ลงเวลาเข้างาน (Check-in)",
        "att_btn_checkout": "ลงเวลาออกงาน (Check-in)",
        "att_recorded_in": "บันทึกเวลาเข้าแล้ว:",
        "att_checked_in_at": "คุณเข้างานเมื่อเวลา:",
        "att_today_complete": "วันนี้คุณลงเวลาครบถ้วนแล้ว",
        "att_label_in": "เข้า",
        "att_label_out": "ออก",
        "att_camera_live": "กล้องถ่ายภาพจริง",
        "att_camera_error": "ไม่สามารถเข้าถึงกล้องได้ กรุณาตรวจสอบสิทธิ์การใช้งานกล้อง",
        "att_lang_code": "th-TH",
        # --- Manual Attendance Form ---
        "man_title": "ยื่นคำขอลงเวลาย้อนหลัง (กรณีลืมลงเวลา)",
        "man_date_label": "วันที่ที่ต้องการลงเวลา",
        "man_date_help": "ระบุวันที่ที่คุณลืมสแกนนิ้วหรือลืมลงเวลา",
        "man_in_label": "เวลาเข้างาน",
        "man_out_label": "เวลาเลิกงาน",
        "man_reason_label": "ระบุเหตุผลที่ลืมลงเวลา",
        "man_reason_placeholder": "เช่น ลืมโทรศัพท์, ติดลูกค้าหน้าเคาน์เตอร์...",
        "man_btn_submit": "ส่งคำร้องขออนุมัติ",
        "man_btn_sending": "กำลังส่งคำขอ...",
        "man_btn_cancel": "ยกเลิก",
        # --- My Attendance Page ---
        "my_att_title": "ประวัติการลงเวลาของฉัน",
        "my_att_col_date": "วันที่",
        "my_att_col_in": "เวลาเข้า",
        "my_att_col_late": "สาย (นาที)",
        "my_att_col_out": "เวลาออก",
        "my_att_col_early": "ออกก่อน (นาที)",
        "my_att_col_status": "สถานะ",
        "my_att_status_normal": "ปกติ",
        "my_att_status_late": "สาย",
        "my_att_status_absent": "ขาดงาน",
        "my_att_status_holiday": "วันหยุด",
        "my_att_no_data": "ยังไม่มีประวัติการลงเวลา",
        # --- Leave Application Form ---
        "lv_back": "กลับ",
        "lv_title": "แบบฟอร์มใบลา",
        "lv_type_label": "ประเภทการลา",
        "lv_type_select": "--- เลือกประเภทการลา ---",
        "lv_type_sick": "ลาป่วย",
        "lv_type_personal": "ลากิจ",
        "lv_type_vacation": "ลาพักร้อน",
        "lv_type_other": "ลาอื่นๆ",
        "lv_start_date": "เริ่มวันที่",
        "lv_end_date": "ถึงวันที่",
        "lv_start_time": "ตั้งแต่เวลา",
        "lv_end_time": "ถึงเวลา",
        "lv_full_day_note": "* กรณีลาเต็มวัน ให้ระบุเป็นเวลาเริ่มงานถึงเวลาเลิกงานปกติ",
        "lv_reason_label": "เหตุผลการลา",
        "lv_reason_placeholder": "ระบุรายละเอียดความจำเป็น...",
        "lv_file_label": "แนบเอกสารประกอบ (ถ้ามี)",
        "lv_file_help": "รองรับไฟล์ภาพ หรือ PDF (เช่น ใบรับรองแพทย์)",
        "lv_btn_submit": "ส่งคำขออนุมัติลา",
        # --- My Leaves Page ---
        "ml_title": "ประวัติการลาของฉัน",
        "ml_btn_new": "เขียนใบลาใหม่",
        "ml_quota_sick": "ลาป่วยคงเหลือ",
        "ml_quota_personal": "ลากิจคงเหลือ",
        "ml_quota_vacation": "พักร้อนคงเหลือ",
        "ml_unit_day": "วัน",
        "ml_col_submit": "วันที่ยื่น",
        "ml_col_type": "ประเภท",
        "ml_col_date": "วันที่ลา",
        "ml_col_reason": "เหตุผล",
        "ml_col_status": "สถานะ",
        "ml_status_pending": "รออนุมัติ",
        "ml_status_approved": "อนุมัติแล้ว",
        "ml_status_rejected": "ปฏิเสธ",
        "ml_no_data": "ยังไม่มีประวัติการลา",
        # Mapping ประเภทการลา
        "type_sick": "ลาป่วย",
        "type_personal": "ลากิจ",
        "type_vacation": "ลาพักร้อน",
        "type_other": "ลาอื่นๆ",
        # Payroll ประเภทการลา
        "pay_title": "คำนวณเงินเดือน",
        "pay_select_range": "📅 เลือกช่วงเวลาคำนวณรอบเงินเดือน",
        "pay_start": "เริ่ม",
        "pay_end": "ถึง",
        "pay_btn_fetch": "ดึงข้อมูล",
        "pay_col_name": "ชื่อพนักงาน",
        "pay_col_base": "เงินเดือน+ตำแหน่ง",
        "pay_col_stats": "สถิติ สาย/ขาด",
        "pay_col_ot": "OT (บาท)",
        "pay_col_late": "หักสาย",
        "pay_col_early": "หักออกก่อน",
        "pay_col_absent": "หักขาดงาน",
        "pay_col_extra_inc": "เงินเพิ่มพิเศษ",
        "pay_col_extra_ded": "เงินลดพิเศษ",
        "pay_col_sso": "SSO",
        "pay_col_tax": "Tax",
        "pay_col_net": "รวมสุทธิ",
        "pay_stat_late": "สาย",
        "pay_stat_early": "ออกก่อน",
        "pay_stat_absent": "ขาดงาน",
        "pay_unit_min": "น.",
        "pay_unit_day": "วัน",
        "pay_btn_save_draft": "บันทึกร่าง",
        "pay_btn_finalize": "ประมวลผลเสร็จสิ้น",
        "pay_confirm_finalize": "ยืนยันการประมวลผลเสร็จสิ้น?",
        # --- Payroll Summary Page ---
        "ps_title": "รายงานรายละเอียดเงินเดือนรวม",  # noqa: F601
        "ps_btn_export": "Export Excel",
        "ps_btn_new_calc": "คำนวณงวดใหม่",
        "ps_label_month": "📅 งวดประจำเดือน",
        "ps_label_year": "ปี (พ.ศ.)",
        "ps_btn_search": "เรียกดูข้อมูล",
        "ps_col_name": "ชื่อพนักงาน",
        "ps_header_income": "รายการรายได้ (Incomes)",
        "ps_header_deduct": "รายการหัก (Deductions)",
        "ps_col_net": "สุทธิ (Net)",
        "ps_col_slip": "สลิป",
        "ps_sub_salary": "เงินเดือน/ตำแหน่ง",
        "ps_sub_ot": "โอที (OT)",
        "ps_sub_extra_inc": "เงินเพิ่มอื่นๆ",
        "ps_sub_total_inc": "รวมรายได้",
        "ps_sub_absent": "หักขาด/สาย",
        "ps_sub_sso": "SSO",
        "ps_sub_tax": "Tax",
        "ps_sub_extra_ded": "หักอื่นๆ",
        "months": ["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"],
        # --- Tax & SSO Report Page ---
        "tax_title": "รายงานนำส่ง SSO และ ภาษี (ภ.ง.ด.1)",
        "tax_select_cycle": "📅 เลือกงวดรายงาน",
        "tax_label_year": "ปี (พ.ศ.)",
        "tax_btn_view": "ดูรายงาน",
        "tax_summary_sso": "รวมนำส่งประกันสังคม (SSO)",
        "tax_summary_withholding": "รวมภาษีหัก ณ ที่จ่าย (ภ.ง.ด.1)",
        "tax_col_no": "ลำดับ",
        "tax_col_name": "ชื่อพนักงาน",
        "tax_col_gross": "ยอดเงินได้ทั้งหมด",
        "tax_col_sso": "SSO (5%)",
        "tax_col_withholding": "ภาษี (หัก ณ ที่จ่าย)",
        "tax_no_data": "ไม่พบข้อมูลการจ่ายเงินในงวดที่เลือก",
        # --- My Payslips Page ---
        "psl_title": "ประวัติรายได้และใบแจ้งเงินเดือน",
        "psl_subtitle": "เลือกช่วงเวลาเพื่อดูหรือพิมพ์ใบแจ้งเงินเดือนของคุณ",
        "psl_filter_btn": "ค้นหา",
        "psl_header_main": "ใบแจ้งเงินเดือน (Payslip)",
        "psl_period": "ประจำงวดเดือน",
        "psl_emp_id": "รหัสพนักงาน",
        "psl_full_name": "ชื่อ-นามสกุล",
        "psl_earnings": "รายการรายได้ (Earnings)",
        "psl_deductions": "รายการหัก (Deductions)",
        "psl_salary_pos": "เงินเดือน/ตำแหน่ง",
        "psl_ot": "ค่าล่วงเวลา (OT)",
        "psl_extra_inc": "เงินเพิ่มพิเศษ",
        "psl_sso": "ประกันสังคม (SSO)",
        "psl_tax": "ภาษีหัก ณ ที่จ่าย",
        "psl_absence": "หักขาด/สาย",
        "psl_extra_ded": "เงินลดพิเศษ/อื่นๆ",
        "psl_net_payable": "ยอดรับสุทธิ (Net Payable)",
        "psl_baht": "บาท",
        "psl_sig_emp": "ลายมือชื่อพนักงาน (Employee Signature)",
        "psl_sig_auth": "ผู้อนุมัติจ่าย (Authorized Signature)",
        "psl_print_this": "พิมพ์ใบแจ้งเงินเดือนนี้",
        "psl_no_data": "ไม่พบข้อมูลเงินเดือนในงวดนี้",
        "psl_contact_hr": "หากคุณคิดว่านี่คือข้อผิดพลาด โปรดติดต่อแผนกบุคคล",
        "psl_department": "แผนก",
        "psl_department_general": "ทั่วไป",
        "psl_default_address": "123/45 ถนนหลัก แขวง/ตำบล เขต/อำเภอ\nกรุงเทพมหานคร 10xxx\nโทร. 02-xxx-xxxx",
        "psl_auto_note": "เอกสารนี้สร้างโดยระบบอัตโนมัติ Mini-HRM ไม่ต้องมีผู้ลงนามก็มีผลสมบูรณ์",
        "psl_print_pdf": "พิมพ์เอกสาร / เซฟเป็น PDF",
        "months_short": ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],
        "months_full": ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],
        # --- OT Request Page ---
        "ot_title": "ยื่นคำขอโอที (OT Request)",
        "ot_work_date": "วันที่ปฏิบัติงาน",
        "ot_start_time": "เวลาเริ่ม",
        "ot_end_time": "เวลาสิ้นสุด",
        "ot_type_label": "ประเภทโอที",
        "ot_type_1_5": "OT 1.5 เท่า (วันทำงานปกติ)",
        "ot_type_1_0": "OT 1.0 เท่า (วันหยุด - เวลาปกติ)",
        "ot_type_2_0": "OT 2.0 เท่า (วันหยุด - นอกเวลา)",
        "ot_type_3_0": "OT 3.0 เท่า (นักขัตฤกษ์)",
        "ot_reason_label": "เหตุผลการทำโอที",
        "ot_reason_placeholder": "เช่น ทำงานล่วงเวลา หรือ เคลียร์เคสคนไข้",
        "ot_btn_submit": "ส่งคำขออนุมัติ",
        "ot_msg_missing_fields": "กรุณากรอกข้อมูลวันที่และช่วงเวลา OT ให้ครบถ้วน",
        "ot_msg_invalid_time": "ช่วงเวลา OT ไม่ถูกต้อง กรุณาตรวจสอบเวลาเริ่มและเวลาสิ้นสุด",
        "ot_msg_overlap_time": "ไม่สามารถยื่น OT ได้ เนื่องจากช่วงเวลาทับซ้อนกับคำขอเดิมในวันเดียวกัน",
        "ot_msg_error": "เกิดข้อผิดพลาดระหว่างบันทึกคำขอ OT กรุณาลองใหม่อีกครั้ง",
        # --- My OT History Page ---
        "oth_title": "ประวัติการขอโอทีของฉัน",
        "oth_btn_new": "ขอโอทีใหม่",
        "oth_col_date": "วันที่",
        "oth_col_time": "ช่วงเวลา",
        "oth_col_min": "นาที",
        "oth_col_type": "ประเภท",
        "oth_col_status": "สถานะ",
        "oth_status_pending": "รออนุมัติ",
        "oth_status_approved": "อนุมัติแล้ว",
        "oth_status_rejected": "ไม่นุมัติ",
        "oth_remark_label": "หมายเหตุ:",
        "oth_no_data": "ยังไม่มีประวัติการขอโอที",
        # --- My Profile Page ---
        "pro_my_profile": "โปรไฟล์ของฉัน",
        "pro_no_photo": "ไม่มีรูปถ่าย",
        "pro_code": "รหัสพนักงาน:",
        "pro_pos": "ตำแหน่ง:",
        "pro_dept": "แผนก:",
        "pro_phone": "เบอร์โทร:",
        "pro_id_card": "เลขบัตรประชาชน:",
        "pro_bank": "เลขบัญชี:",
        "pro_base_salary": "ฐานเงินเดือน:",
        "pro_pos_allowance": "ค่าตำแหน่ง:",
        "pro_address_title": "ที่อยู่:",
        "pro_no_address": "ไม่ได้ระบุข้อมูลที่อยู่",
        "pro_doc_title": "เอกสารประกอบการสมัคร:",
        "pro_no_doc": "ไม่มีเอกสารที่อัปโหลดไว้",
        "pro_unit_baht": "บาท",
        # --- Notification Section ---
        "pro_notif_title": "การแจ้งเตือนระบบ",
        "pro_notif_desc": "รับการแจ้งเตือนทันทีเมื่อใบลาได้รับการอนุมัติ หรือแจ้งเตือนลืมลงเวลา",
        "pro_notif_btn": "เปิดการแจ้งเตือนบนมือถือเครื่องนี้",
        "pro_notif_unsupported": "เบราว์เซอร์นี้ไม่รองรับการแจ้งเตือนครับ",
        "pro_notif_denied": "โปรดอนุญาตสิทธิ์การแจ้งเตือนในการตั้งค่าครับ",
        "pro_notif_success": "🎉 เปิดการแจ้งเตือนสำเร็จ!",
        "pro_notif_error": "เกิดข้อผิดพลาดในการเปิดการแจ้งเตือน",
        # --- Change Password Page ---
        "pw_title": "เปลี่ยนรหัสผ่านใหม่",
        "pw_old_label": "รหัสผ่านเดิม",
        "pw_new_label": "รหัสผ่านใหม่",
        "pw_confirm_label": "ยืนยันรหัสผ่านใหม่",
        "pw_btn_submit": "ยืนยันการเปลี่ยนรหัสผ่าน",
        "pw_btn_cancel": "ยกเลิก",
        # --- Company Settings Page ---
        "com_title": "ตั้งค่าสถานประกอบการ",
        "com_badge": "ใช้สำหรับแสดงข้อมูลในสลิปเงินเดือน",
        "com_logo_label": "โลโก้ร้าน / บริษัท",
        "com_no_logo": "ยังไม่มีโลโก้",
        "com_logo_help": "แนะนำไฟล์ PNG/JPG ขนาด 300x300 px (ระบบจะคัดลอกไฟล์อัตโนมัติ)",
        "com_name_label": "ชื่อสถานประกอบการ",
        "com_name_placeholder": "เช่น Clinic HRM Center",
        "com_name_help": "ชื่อนี้จะปรากฏเป็นตัวหนาในส่วนหัวของสลิปเงินเดือน",
        "com_address_label": "ที่อยู่และเบอร์โทรศัพท์ติดต่อ",
        "com_address_placeholder": "ระบุที่อยู่ เช่น... ถนน... แขวง... โทร...",
        "com_address_help": "ข้อมูลจะแสดงผลตามบรรทัดที่คุณกรอก (ขึ้นบรรทัดใหม่ได้อิสระ)",
        "com_btn_update": "อัปเดตข้อมูลและใช้ในสลิปทันที",
        "com_msg_success": "บันทึกข้อมูลบริษัทเรียบร้อยแล้ว",
        # --- Payroll Settings Page ---
        "ps_subtitle": "กำหนดตัวหารและตัวคูณสำหรับใช้ในระบบคำนวณอัตโนมัติ",
        "ps_section_deduct": "ส่วนการหักเงิน",
        "ps_header_late": "⚙️ สูตรหักเงิน (สาย / ออกก่อน)",
        "ps_header_absent": "⚙️ สูตรหักเงิน (ขาดงาน)",
        "ps_section_ot": "ส่วนค่าล่วงเวลา (OT)",
        "ps_header_ot_main": "⚙️ สูตรคำนวณ OT (ปกติ x1.5)",
        "ps_header_ot_multi": "⚙️ ตัวคูณ OT ประเภทเพิ่มเติม",
        "ps_label_day_divider": "ตัวหารวัน",
        "ps_label_hour_divider": "ตัวหารชั่วโมง",
        "ps_label_multiplier": "ตัวคูณ (Multiplier)",
        "ps_help_absent": "เช่น 30 หรือ 26 วัน",
        "ps_formula_late": "* สูตร: (เงินเดือน / วัน / ชม. / 60) * นาทีที่สาย",
        "ps_formula_absent": "* สูตร: (เงินเดือน / วัน) * จำนวนวันที่ขาด",
        "ps_formula_ot": "* สูตร: (เงินเดือน / วัน / ชม. / 60) * นาที OT * ตัวคูณ",
        "ps_formula_ot_ref": "* ตัวหารวัน/ชม. อ้างอิงจากตั้งค่า OT ปกติ",
        "ps_btn_save": "บันทึกการตั้งค่าทั้งหมด",
        "emp_status_active": "พนักงานปัจจุบัน",
        "emp_status_resigned": "พนักงานที่ลาออกแล้ว",
        "emp_btn_resign": "แจ้งลาออก",
        "emp_btn_restore": "ดึงกลับเป็นพนักงาน",
        "emp_confirm_resign": "ยืนยันการเปลี่ยนสถานะเป็นลาออก? (พนักงานจะเข้าระบบไม่ได้และไม่แสดงในงวดเงินเดือน)",
        # Navbar & Sidebar
        "nav_home": "แดชบอร์ด",
        "nav_monitor": "ระบบมอนิเตอร์",
        "nav_leave": "ระบบลาพักผ่อน",
        "nav_settings": "ตั้งค่า",
        "nav_logout": "ออกจากระบบ",
        "nav_audit_log": "ประวัติการใช้งาน",

        # Monitor Page (Statistics)
        "mon_title": "ระบบ Monitor สถิติพนักงาน",
        "mon_last_update": "ข้อมูลล่าสุด",
        "mon_total_emp": "พนักงานทั้งหมด",
        "mon_present": "เข้างานปกติ",
        "mon_on_leave": "ลางานวันนี้",
        "mon_pending": "รออนุมัติการลา",
        "mon_absent_today": "ขาดวันนี้",
        "mon_late_today": "สายวันนี้",
        "mon_early_today": "ออกก่อนวันนี้",
        "mon_chart_monthly": "สถิติการลางาน 6 เดือนล่าสุด",
        "mon_chart_pie": "สัดส่วนประเภทการลา",
        "mon_attendance_monthly": "สถิติการเข้างานประจำเดือน",
        "mon_pie_normal": "ปกติ",
        "mon_pie_late": "มาสาย",
        "mon_pie_absent": "ขาด",
        "mon_pie_leave": "ลา",
        "mon_chart_unit": "ครั้ง",
    
        # Leave Types
        "leave_sick": "ลาป่วย",
        "leave_personal": "ลากิจ",
        "leave_vacation": "ลาพักร้อน",

        # PDPA Consent Modal
        "pdpa_title": "การคุ้มครองข้อมูลส่วนบุคคล (PDPA)",
        "pdpa_description": "เราให้ความสำคัญกับการคุ้มครองข้อมูลส่วนบุคคลของคุณ เพื่อให้คุณมั่นใจว่าข้อมูลจะถูกจัดเก็บและใช้งานอย่างปลอดภัยตามนโยบายของบริษัท",
        "pdpa_purpose_title": "วัตถุประสงค์การใช้ข้อมูล:",
        "pdpa_purpose_1": "เพื่อใช้ในการบริหารจัดการงานบุคคลภายใน",
        "pdpa_purpose_2": "เพื่อบันทึกประวัติการมาทำงานและการลางาน",
        "pdpa_purpose_3": "เพื่อใช้ในการคำนวณสวัสดิการและค่าตอบแทน",
        "pdpa_dont_show": "รับทราบและไม่ต้องแสดงข้อความนี้อีก",
        "pdpa_btn_accept": "ยินยอมและเข้าใช้งาน",

        # Login / Common
        "login_welcome": "ยินดีต้อนรับสู่ระบบ HRM",
        "login_btn": "เข้าสู่ระบบ",
        "msg_inactive": "บัญชีของคุณถูกระงับ กรุณาติดต่อแอดมิน",
        "msg_expired": "เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่",# เพิ่มในก้อนภาษาไทย (texts_th)
        "log_title": "ระบบ Audit Log",
        "log_subtitle": "ประวัติการใช้งานระบบ",
        "log_refresh": "รีเฟรชข้อมูล",
        "log_col_time": "วัน-เวลา",
        "log_col_user": "ผู้ดำเนินการ",
        "log_col_action": "ประเภทกิจกรรม",
        "log_col_details": "รายละเอียด",
        "log_col_ip": "IP Address",
        "log_search": "ค้นหาใน Log:",
        "log_info_show": "แสดงรายการที่ _START_ ถึง _END_ จากทั้งหมด _TOTAL_ รายการ",
        "log_no_data": "ไม่มีข้อมูลในตาราง",
        
        # OT Summary Report (Thai)
        "ot_sum_title": "สรุปข้อมูลค่าล่วงเวลา (OT)",
        "ot_sum_start_date": "วันที่เริ่มต้น",
        "ot_sum_end_date": "วันที่สิ้นสุด",
        "ot_sum_status": "สถานะ",
        "ot_sum_all": "ทั้งหมด",
        "ot_sum_pending": "รอการอนุมัติ",
        "ot_sum_approved": "อนุมัติแล้ว",
        "ot_sum_rejected": "ปฏิเสธ",
        "ot_sum_search": "ค้นหา",
        "ot_sum_header_total": "รวมทั้งหมด",
        "ot_sum_header_approved": "อนุมัติแล้ว",
        "ot_sum_header_pending": "รออนุมัติ",
        "ot_sum_header_rejected": "ปฏิเสธ",
        "ot_sum_items": "รายการ",
        "ot_sum_hours": "ชั่วโมง",
        "ot_sum_record": "รายการ OT",
        "ot_sum_no_data": "ไม่พบข้อมูล",
        "ot_sum_period": "ในช่วงเวลาที่เลือก",
        "ot_sum_header_summary": "สรุปข้อมูลทั่วไป",
        "ot_sum_total_hours": "รวมชั่วโมง",
        "ot_sum_by_type": "สรุปตามประเภท OT",
        "ot_sum_type_1_0": "OT 1.0 เท่า",
        "ot_sum_type_1_5": "OT 1.5 เท่า",
        "ot_sum_type_2_0": "OT 2.0 เท่า",
        "ot_sum_type_3_0": "OT 3.0 เท่า",
        "ot_sum_details_title": "รายละเอียดข้อมูล OT",
        "ot_sum_export_excel": "ส่งออก Excel",
        "ot_sum_col_date": "วันที่",
        "ot_sum_col_employee": "พนักงาน",
        "ot_sum_col_time": "เวลา",
        "ot_sum_col_type": "ประเภท",
        "ot_sum_col_minutes": "นาที",
        "ot_sum_col_hours": "ชั่วโมง",
        "ot_sum_col_reason": "เหตุผล",
        "ot_sum_col_status": "สถานะ",
        "ot_sum_col_remark": "หมายเหตุ",
        "ot_sum_badge_approved": "✓ อนุมัติแล้ว",
        "ot_sum_badge_pending": "⧖ รอการอนุมัติ",
        "ot_sum_badge_rejected": "✗ ปฏิเสธ",
        "ot_sum_empty_remark": "ไม่มี",
        "ot_sum_no_data_in_period": "ไม่พบข้อมูล OT ในช่วงเวลาที่เลือก",
        "ot_sum_export_no_data": "ไม่พบข้อมูลสำหรับส่งออก",

        "ot_report_title": "สรุปภาพรวมค่าล่วงเวลา (OT)",
        "ot_report_minute_unit": "นาที",
        "ot_report_col_date": "วันที่",
        "ot_report_col_employee": "พนักงาน",
        "ot_report_col_type": "ประเภท",
        "ot_report_col_minutes": "นาที",
        "ot_report_col_reason": "เหตุผล",

        # Payroll Form (Thai)
        "pay_subtitle": "สรุปการคำนวณ",
        "pay_period_info": "ช่วงวัน",
        "pay_base_salary": "ฐาน (เดือน)",
        "pay_stats": "สถิติ (วัน/สาย/ขาด)",
        "pay_late_early": "หักสาย/ออก",
        "pay_absent": "หักขาด",
        "pay_bonus": "เงินเพิ่ม/ลด",
        "pay_sso_tax": "SSO / Tax",
        "pay_recalc_new": "คำนวณใหม่",
        "pay_recalc_late": "รีคำนวณ Late/Early",
        "pay_clear_draft": "ล้าง Draft",
        "pay_confirm_clear": "ยืนยันการรีเซ็ตสถิติใหม่? ระบบจะล้างข้อมูลที่คุณเคยบันทึกร่างไว้ และนับนาที สาย/ขาด/ออกก่อน ใหม่ทั้งหมดตามจริง",
        "pay_recalc_success": "✅ รีคำนวณค่า Late/Early เรียบร้อยแล้ว! กรุณากดปุ่ม \"คำนวณใหม่\" เพื่อดูผลลัพธ์",
        "pay_recalc_error": "❌ เกิดข้อผิดพลาดในการรีคำนวณ",
        "pay_error_date_range": "คำนวณวันที่ต่างจากรอบปกติของเดือน",
        "pay_label_late": "สาย",
        "pay_label_early": "ออกก่อน",
        "pay_label_absent": "ขาดงาน",
        "pay_label_extra": "เพิ่ม",
        "pay_label_deduct": "ลด",
        "pay_label_sso": "SSO",
        "pay_label_tax": "TAX",
        "unit_day": "วัน",
        "unit_min": "น.",
        "pay_yellow_note": "แถบสีเหลือง = คำนวณวันที่ต่างจากรอบปกติของเดือน",
        "pay_save_draft": "บันทึกร่าง (Draft)",
        "pay_finalize": "ยืนยันจ่ายเงินเดือน",
        "pay_confirm_finalize": "ยืนยันยอดเงินเดือนทั้งหมด? พนักงานจะสามารถดูสลิปได้ทันที",
        "pay_recalc_confirm": "⚠️ ต้องการรีคำนวณค่าเวลาสายและออกก่อนใหม่หรือไม่?\n\nระบบจะคำนวณใหม่ตามตารางเวลาปัจจุบันของพนักงาน",
        "pay_select_dates_first": "กรุณาเลือกช่วงวันที่ก่อน",
        "pay_csrf_missing": "ไม่พบ CSRF token กรุณารีเฟรชหน้าแล้วลองใหม่อีกครั้ง",
        
        # Leave Types (Thai translation mapping)
        "leave_type_sick": "ลาป่วย",
        "leave_type_personal": "ลากิจ",
        "leave_type_vacation": "ลาพักร้อน",
        "leave_type_other": "ลาอื่นๆ",
        
        # Additional UI elements
        "nav_ot_summary": "สรุป OT",
    },
    "en": {
        # --- Navbar ---
        "nav_emp": "Employees",
        "nav_emp_list": "Employee List",
        "nav_add_emp": "Add Employee",
        "nav_broadcast": "Broadcast",
        "nav_time_mgmt": "Time Management",
        "nav_set_schedule": "Set Schedules",
        "nav_check_leaves": "Check Leaves",
        "nav_approve_manual": "Approve Manual Time",
        "nav_holidays": "Holidays",
        "nav_leave_summary": "Leave Summary",
        "nav_attendance_report": "Attendance Report",
        "nav_record_time": "Time & Leave",
        "nav_header_personal": "Time & Profile",
        "nav_checkin": "Check-in",
        "nav_forgot_time": "Forgot to Check-in",
        "nav_my_attendance": "My Attendance",
        "nav_header_leave": "Leave Request",
        "nav_apply_leave": "Apply for Leave",
        "nav_my_leaves": "My Leaves",
        "nav_payroll_ot": "Payroll & OT",
        "nav_header_admin_payroll": "Payroll Management (Admin)",
        "nav_calc_payroll": "Calculate Payroll",
        "nav_payroll_summary": "Payroll Summary",
        "nav_tax_sso": "Tax & SSO Report",
        "nav_approve_ot": "Approve OT",
        "nav_header_staff": "For Staff",
        "nav_payslip": "Payslip",
        "nav_req_ot": "Request OT",
        "nav_my_ot": "My OT Requests",
        "nav_hello": "Hello",
        "nav_my_profile": "My Profile",
        "nav_change_pw": "Change Password",
        "nav_header_sys_settings": "System Settings",
        "nav_payroll_formula": "Payroll Formula",
        "nav_org_settings": "Org Settings & Logo",
        "nav_logout": "Logout",

        # --- Dashboard Page ---
        "employees_list": "Employee List",
        "add_employee": "Add New Employee",
        "save_success": "Saved Successfully!",
        "update_success": "Updated Successfully!",
        "delete_success": "Employee Deleted",
        "photo": "Photo",
        "employee_code": "Employee ID",
        "full_name": "Full Name",
        "position": "Position",
        "phone": "Phone",
        "role": "Role",
        "manage": "Manage",
        "view_info": "View",
        "edit": "Edit",
        "manage_quota": "Quota",
        "delete": "Delete",
        "confirm_delete": "Delete this employee?",
        "employee_details": "Employee Details",
        "close": "Close",
        "loading_error": "Error loading data",

        # --- Add Employee Page ---
        "add_emp_title": "Add New Employee",
        "emp_code": "Employee ID",
        "first_name": "First Name",
        "last_name": "Last Name",
        "nickname": "Nickname",
        "id_card": "ID Card No.",
        "pos_dept": "Position/Dept.",
        "set_password": "Set Password *",
        "pw_placeholder": "Min. 4 characters",
        "address": "Address",
        "base_salary": "Base Salary",
        "pos_allowance": "Position Allowance",
        "bank_acc": "Bank Account No.",
        "system_role": "System Role",
        "profile_pic": "Profile Photo (JPG/PNG)",
        "docs": "Job Documents (Multi PDF)",
        "sick_quota": "Sick Leave Quota",
        "personal_quota": "Personal Leave Quota",
        "vacation_quota": "Vacation Quota",
        "cancel": "Cancel",
        "reset": "Reset",
        "save_emp": "Save Employee",
        "doctor": "Doctor",
        "nurse": "Dental Assistant",
        "staff": "Staff",

        # --- Edit Employee Page ---
        "edit_emp_title": "Edit Employee Information",
        "change_profile_pic": "Change Profile Photo (Optional)",
        "add_docs": "Add PDF Documents (Optional)",
        "set_leave_quota": "Set Leave Quota Per Year (Days)",
        "save_changes": "Save All Changes",
        "back": "Back",

        # --- Import Attendance Page ---
        "import_att_title": "Import Attendance Data (Excel)",
        "import_att_format_header": "Supported File Format:",
        "import_att_format_desc": "File must have these column headers",
        "import_att_columns": "Select Excel File (.xlsx)",
        "import_att_btn": "Start Importing Data into System",

        # --- OT Approval Page ---
        "ot_approval_title": "OT Approval",
        "emp_id": "Employee ID",
        "request_date": "Request Date",
        "time_range": "Time Range",
        "total_minutes": "Total Minutes",
        "ot_type": "OT Type",
        "reason": "Reason",
        "minute_unit": "min.",
        "placeholder_remark": "Enter remark",
        "approve": "Approve",
        "reject": "Reject",
        "confirm_reject": "Confirm reject?",
        "no_pending_ot": "No pending requests",
        # --- Broadcast Page ---
        "broadcast_title": "Broadcast to All Employees",
        "broadcast_subject": "Broadcast Subject",
        "broadcast_placeholder_title": "e.g., Office Closing Notice",
        "broadcast_message": "Message Content",
        "broadcast_placeholder_msg": "Enter details for employees...",
        "broadcast_info": "This message will appear on the lock screen of employees who enabled notifications.",
        "broadcast_btn": "Send Broadcast Now",
        "broadcast_confirm": "Confirm sending broadcast to all employees?",
        # --- Schedule Page ---
        "sch_title": "Individual Work Schedule & Holidays",
        "sch_emp": "Employee",
        "sch_check_in": "Shift Start",
        "sch_check_out": "Shift End",
        "sch_time": "Time",
        "sch_late_min": "Grace Late (m)",
        "sch_early_min": "Grace Early (m)",
        "sch_work_days": "Working Days (Check to set as workday)",
        "sch_guide_title": "Setup Guidelines",
        "sch_guide_1": "Workdays: Checked = Required | Unchecked = Weekly Off",
        "sch_guide_2": "Calculation: 'Absent' status only applies to designated workdays",
        "sch_guide_3": "Impact: Ideal for managing rotating shifts and different off-days",
        "sch_save_btn": "Save All Schedules",
        # Days short
        "day_mon": "Mon", "day_tue": "Tue", "day_wed": "Wed", "day_thu": "Thu", 
        "day_fri": "Fri", "day_sat": "Sat", "day_sun": "Sun",
        # --- Leave Approval Page ---
        "leave_list_title": "Leave Requests List",
        "leave_submit_date": "Submission Date",
        "leave_emp_name": "Employee",
        "leave_type_label": "Type",
        "leave_date_range": "Leave Dates",
        "leave_reason": "Reason",
        "leave_evidence": "Evidence",
        "leave_status": "Status",
        "leave_manage": "Action/Remark",
        "leave_view_file": "View File",
        "leave_no_file": "None",
        "leave_pending": "Pending",
        "leave_approved": "Approved",
        "leave_rejected": "Rejected",
        "leave_reason_header": "Reason",
        "leave_approve_btn": "Approve",
        "leave_reject_btn": "Reject",
        "leave_confirm_reject": "Confirm reject this leave request?",
        "leave_no_data": "No leave requests at this time",
        "leave_managed_at": "Managed at",
        "leave_remark_placeholder": "Remark (optional for rejection)",
        # --- Attendance Requests Page ---
        "att_mgmt_title": "Attendance Requests Management",
        "att_approve_all": "Approve All",
        "att_import_excel": "Import from Excel",
        "att_import_title": "Import Attendance Data",
        "att_import_template_msg": " Please use our template for 100% accuracy.",
        "att_download_template": "Download Excel Template",
        "att_select_file": "Select File (.xlsx, .csv)",
        "att_start_import": "Start Import",
        "att_col_req_date": "Request Date",
        "att_col_emp": "Employee",
        "att_col_att_date": "Attendance Date",
        "att_col_time": "Time (In/Out)",
        "att_col_reason": "Reason / Notes",
        "att_col_location": "Location",
        "att_col_actions": "Actions",
        "att_no_pending": "No pending requests found.",
        "att_confirm_approve_all": "Approve all pending requests?",
        "att_confirm_approve": "Approve this request?",
        "att_confirm_reject": "Reject this request?",
        # --- Holidays Page ---
        "hld_title": "Public Holidays Management",
        "hld_label_date": "Holiday Date",
        "hld_label_name": "Holiday Name",
        "hld_placeholder_name": "e.g., Songkran Festival",
        "hld_btn_save": "Save Holiday",
        "hld_col_date": "Date",
        "hld_col_name": "Holiday Name",
        "hld_col_manage": "Action",
        "hld_btn_delete": "Delete",
        "hld_no_data": "No public holidays defined",
        "hld_confirm_delete": "Are you sure you want to delete this holiday?",
        # --- Leave Summary Page ---
        "ls_title": "Employee Leave & Quota Summary",
        "ls_print_btn": "Print Report",
        "ls_col_emp": "Employee",
        "ls_col_sick": "Sick Leave (Left/Quota)",
        "ls_col_personal": "Personal Leave (Left/Quota)",
        "ls_col_vacation": "Vacation (Left/Quota)",
        "ls_col_status": "Status",
        "ls_unit_day": "d",
        "ls_status_active": "Active",
        "ls_status_inactive": "Inactive",
        "ls_id_label": "ID",
        # --- Attendance Report Page ---
        "rep_title": "Attendance Summary Report",
        "rep_from": "From Date",
        "rep_to": "To Date",
        "rep_search_label": "Search Employee (Name or ID)",
        "rep_search_placeholder": "Enter name or employee code...",
        "rep_btn_search": "Search",
        "rep_btn_export": "Export Excel",
        "rep_period_label": "Report Period:",
        "rep_to_label": "to",
        "rep_col_date": "Date",
        "rep_col_code": "Emp ID",
        "rep_col_name": "Full Name",
        "rep_col_in": "Clock In",
        "rep_col_late": "Late (m)",
        "rep_col_out": "Clock Out",
        "rep_col_early": "Early (m)",
        "rep_col_status": "Status",
        "rep_col_photo": "Photo",
        "rep_col_gps": "GPS",
        "rep_status_normal": "Normal",
        "rep_status_absent": "Absent",
        "rep_status_late": "Late",
        "rep_status_abnormal": "Abnormal",
        "rep_status_holiday": "Holiday",
        "rep_photo_in": "In",
        "rep_photo_out": "Out",
        "rep_map_btn": "Map",
        "rep_no_gps": "No GPS",
        "rep_no_data": "No attendance records found for selected period.",
        "rep_modal_title": "Verification Photo",
        "rep_photo_title_in": "Clock-in Photo",
        "rep_photo_title_out": "Clock-out Photo",
        "rep_print_btn": "Print",
        # --- Attendance Page ---
        "att_page_title": "Attendance System (Photo Identity Verification)",
        "att_btn_checkin": "Clock In",
        "att_btn_checkout": "Clock Out",
        "att_recorded_in": "Checked-in at:",
        "att_checked_in_at": "You checked in at:",
        "att_today_complete": "You have completed attendance for today.",
        "att_label_in": "In",
        "att_label_out": "Out",
        "att_camera_live": "Live Camera",
        "att_camera_error": "Cannot access camera. Please check camera permissions.",
        "att_lang_code": "en-US",
        # --- Manual Attendance Form ---
        "man_title": "Manual Attendance Request (Forgot to Clock-in)",
        "man_date_label": "Requested Date",
        "man_date_help": "Select the date you missed your attendance",
        "man_in_label": "Clock-in Time",
        "man_out_label": "Clock-out Time",
        "man_reason_label": "Reason for Manual Request",
        "man_reason_placeholder": "e.g., Forgot phone, Busy with customers...",
        "man_btn_submit": "Submit Request",
        "man_btn_sending": "Sending...",
        "man_btn_cancel": "Cancel",
        # --- My Attendance Page ---
        "my_att_title": "My Attendance History",
        "my_att_col_date": "Date",
        "my_att_col_in": "Clock In",
        "my_att_col_late": "Late (Min)",
        "my_att_col_out": "Clock Out",
        "my_att_col_early": "Early Out (Min)",
        "my_att_col_status": "Status",
        "my_att_status_normal": "Normal",
        "my_att_status_late": "Late",
        "my_att_status_absent": "Absent",
        "my_att_status_holiday": "Holiday",
        "my_att_no_data": "No attendance records found",
        # --- Leave Application Form ---
        "lv_back": "Back",
        "lv_title": "Leave Application Form",
        "lv_type_label": "Leave Type",
        "lv_type_select": "--- Select Leave Type ---",
        "lv_type_sick": "Sick Leave",
        "lv_type_personal": "Personal Leave",
        "lv_type_vacation": "Vacation Leave",
        "lv_type_other": "Other",
        "lv_start_date": "Start Date",
        "lv_end_date": "End Date",
        "lv_start_time": "From Time",
        "lv_end_time": "To Time",
        "lv_full_day_note": "* For full day leave, please use standard working hours.",
        "lv_reason_label": "Reason for Leave",
        "lv_reason_placeholder": "Provide details of your request...",
        "lv_file_label": "Attachments (Optional)",
        "lv_file_help": "Supports Image or PDF (e.g., Medical certificate)",
        "lv_btn_submit": "Submit Leave Request",
        # --- My Leaves Page ---
        "ml_title": "My Leave History",
        "ml_btn_new": "New Leave Request",
        "ml_quota_sick": "Sick Leave Balance",
        "ml_quota_personal": "Personal Leave Balance",
        "ml_quota_vacation": "Vacation Balance",
        "ml_unit_day": "Days",
        "ml_col_submit": "Applied On",
        "ml_col_type": "Type",
        "ml_col_date": "Leave Dates",
        "ml_col_reason": "Reason",
        "ml_col_status": "Status",
        "ml_status_pending": "Pending",
        "ml_status_approved": "Approved",
        "ml_status_rejected": "Rejected",
        "ml_no_data": "No leave history found",
        # Mapping ประเภทการลา
        "type_sick": "Sick Leave",
        "type_personal": "Personal Leave",
        "type_vacation": "Vacation Leave",
        "type_other": "Other",
        # Payroll
        "pay_title": "Calculate Payroll",
        "pay_select_range": "📅 Select Payroll Period",
        "pay_start": "Start",
        "pay_end": "End",
        "pay_btn_fetch": "Fetch Data",
        "pay_col_name": "Employee Name",
        "pay_col_base": "Base + Allowance",
        "pay_col_stats": "Late/Absent Stats",
        "pay_col_ot": "OT (THB)",
        "pay_col_late": "Late Ded.",
        "pay_col_early": "Early Ded.",
        "pay_col_absent": "Absent Ded.",
        "pay_col_extra_inc": "Bonus/Extra",
        "pay_col_extra_ded": "Other Ded.",
        "pay_col_sso": "SSO",
        "pay_col_tax": "Tax",
        "pay_col_net": "Net Salary",
        "pay_stat_late": "Late",
        "pay_stat_early": "Early",
        "pay_stat_absent": "Absent",
        "pay_unit_min": "m",
        "pay_unit_day": "d",
        "pay_btn_save_draft": "Save Draft",
        "pay_btn_finalize": "Finalize Payroll",
        "pay_confirm_finalize": "Confirm to finalize payroll processing?",
        # --- Payroll Summary Page ---
        "ps_title": "Payroll Summary Report",  # noqa: F601
        "ps_btn_export": "Export Excel",
        "ps_btn_new_calc": "New Calculation",
        "ps_label_month": "📅 Monthly Cycle",
        "ps_label_year": "Year (A.D.)",
        "ps_btn_search": "View Data",
        "ps_col_name": "Employee Name",
        "ps_header_income": "Incomes",
        "ps_header_deduct": "Deductions",
        "ps_col_net": "Net Pay",
        "ps_col_slip": "Slip",
        "ps_sub_salary": "Salary/Position",
        "ps_sub_ot": "Overtime",
        "ps_sub_extra_inc": "Other Incomes",
        "ps_sub_total_inc": "Total Income",
        "ps_sub_absent": "Late/Absent",
        "ps_sub_sso": "SSO",
        "ps_sub_tax": "Tax",
        "ps_sub_extra_ded": "Other Ded.",
        "months": ["January","February","March","April","May","June","July","August","September","October","November","December"],
        # --- Tax & SSO Report Page ---
        "tax_title": "SSO & Withholding Tax Report (P.N.D.1)",
        "tax_select_cycle": "📅 Select Report Cycle",
        "tax_label_year": "Year (A.D.)",
        "tax_btn_view": "View Report",
        "tax_summary_sso": "Total Social Security (SSO)",
        "tax_summary_withholding": "Total Withholding Tax",
        "tax_col_no": "No.",
        "tax_col_name": "Employee Name",
        "tax_col_gross": "Gross Income",
        "tax_col_sso": "SSO (5%)",
        "tax_col_withholding": "Withholding Tax",
        "tax_no_data": "No payroll records found for selected period.",
        # --- My Payslips Page ---
        "psl_title": "Income History & Payslips",
        "psl_subtitle": "Select a period to view or print your salary statements.",
        "psl_filter_btn": "Filter",
        "psl_header_main": "Salary Slip (Payslip)",
        "psl_period": "Payment Period",
        "psl_emp_id": "Employee ID",
        "psl_full_name": "Full Name",
        "psl_earnings": "Earnings",
        "psl_deductions": "Deductions",
        "psl_salary_pos": "Salary/Position",
        "psl_ot": "Overtime (OT)",
        "psl_extra_inc": "Extra Income",
        "psl_sso": "Social Security (SSO)",
        "psl_tax": "Withholding Tax",
        "psl_absence": "Absent/Late",
        "psl_extra_ded": "Other Deductions",
        "psl_net_payable": "Net Payable",
        "psl_baht": "THB",
        "psl_sig_emp": "Employee Signature",
        "psl_sig_auth": "Authorized Signature",
        "psl_print_this": "Print This Statement",
        "psl_no_data": "No payslip data found for this period.",
        "psl_contact_hr": "If you believe this is an error, please contact HR department.",
        "psl_department": "Department",
        "psl_department_general": "General",
        "psl_default_address": "123/45 Main Road, Subdistrict\nDistrict, Bangkok 10xxx\nTel. 02-xxx-xxxx",
        "psl_auto_note": "This document is automatically generated by Mini-HRM and is valid without signature.",
        "psl_print_pdf": "Print / Save as PDF",
        "months_short": ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        "months_full": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        # --- OT Request Page ---
        "ot_title": "OT Request Form",
        "ot_work_date": "Work Date",
        "ot_start_time": "Start Time",
        "ot_end_time": "End Time",
        "ot_type_label": "OT Type",
        "ot_type_1_5": "OT 1.5x (Working Day)",
        "ot_type_1_0": "OT 1.0x (Holiday - Regular Hours)",
        "ot_type_2_0": "OT 2.0x (Holiday - After Hours)",
        "ot_type_3_0": "OT 3.0x (Public Holiday)",
        "ot_reason_label": "Reason for OT",
        "ot_reason_placeholder": "e.g., Working late or completing patient cases",
        "ot_btn_submit": "Submit for Approval",
        "ot_msg_missing_fields": "Please fill in work date and OT time period.",
        "ot_msg_invalid_time": "Invalid OT time range. Please verify start and end time.",
        "ot_msg_overlap_time": "Cannot submit OT because the time range overlaps with an existing request on the same day.",
        "ot_msg_error": "An error occurred while saving your OT request. Please try again.",
        # --- My OT History Page ---
        "oth_title": "My OT History",
        "oth_btn_new": "Request New OT",
        "oth_col_date": "Date",
        "oth_col_time": "Period",
        "oth_col_min": "Min",
        "oth_col_type": "Type",
        "oth_col_status": "Status",
        "oth_status_pending": "Pending",
        "oth_status_approved": "Approved",
        "oth_status_rejected": "Rejected",
        "oth_remark_label": "Remark:",
        "oth_no_data": "No OT history found",
        # --- My Profile Page ---
        "pro_my_profile": "My Profile",
        "pro_no_photo": "No Photo",
        "pro_code": "Employee ID:",
        "pro_pos": "Position:",
        "pro_dept": "Department:",
        "pro_phone": "Phone:",
        "pro_id_card": "National ID:",
        "pro_bank": "Bank Account:",
        "pro_base_salary": "Base Salary:",
        "pro_pos_allowance": "Position Allowance:",
        "pro_address_title": "Address:",
        "pro_no_address": "Address not specified",
        "pro_doc_title": "Application Documents:",
        "pro_no_doc": "No documents uploaded",
        "pro_unit_baht": "THB",
        
        # --- Notification Section ---
        "pro_notif_title": "System Notifications",
        "pro_notif_desc": "Get notified immediately when your leave is approved or if you forget to clock in.",
        "pro_notif_btn": "Enable Notifications on this device",
        "pro_notif_unsupported": "This browser does not support notifications.",
        "pro_notif_denied": "Please grant notification permission in your settings.",
        "pro_notif_success": "🎉 Notifications enabled successfully!",
        "pro_notif_error": "Error enabling notifications",
        # --- Change Password Page ---
        "pw_title": "Change Password",
        "pw_old_label": "Old Password",
        "pw_new_label": "New Password",
        "pw_confirm_label": "Confirm New Password",
        "pw_btn_submit": "Update Password",
        "pw_btn_cancel": "Cancel",
        # --- Company Settings Page ---
        "com_title": "Company Settings",
        "com_badge": "Information used for salary slips",
        "com_logo_label": "Company Logo",
        "com_no_logo": "No Logo Uploaded",
        "com_logo_help": "Recommended PNG/JPG 300x300 px (Auto-uploaded to static folder)",
        "com_name_label": "Business Name",
        "com_name_placeholder": "e.g., Clinic HRM Center",
        "com_name_help": "This name will appear bold in the payslip header",
        "com_address_label": "Address & Contact Details",
        "com_address_placeholder": "Enter address e.g. 123 Main St, District, Tel...",
        "com_address_help": "Display follows your line breaks (free text format)",
        "com_btn_update": "Update Info & Sync to Payslips",
        "com_msg_success": "Company information saved successfully",
        # --- Payroll Settings Page ---
        "ps_subtitle": "Define dividers and multipliers for automated payroll calculation",
        "ps_section_deduct": "Deductions Section",
        "ps_header_late": "⚙️ Late / Early Out Deduction",
        "ps_header_absent": "⚙️ Absent Deduction",
        "ps_section_ot": "Overtime (OT) Section",
        "ps_header_ot_main": "⚙️ OT Calculation (Standard x1.5)",
        "ps_header_ot_multi": "⚙️ Additional OT Multipliers",
        "ps_label_day_divider": "Day Divider",
        "ps_label_hour_divider": "Hour Divider",
        "ps_label_multiplier": "Multiplier",
        "ps_help_absent": "e.g., 30 or 26 days",
        "ps_formula_late": "* Formula: (Salary / Day / Hr / 60) * Late Mins",
        "ps_formula_absent": "* Formula: (Salary / Day) * Absent Days",
        "ps_formula_ot": "* Formula: (Salary / Day / Hr / 60) * OT Mins * Multiplier",
        "ps_formula_ot_ref": "* Day/Hour dividers refer to Standard OT settings",
        "ps_btn_save": "Save All Settings",
        "emp_status_active": "Current Employees",
        "emp_status_resigned": "Resigned Employees",
        "emp_btn_resign": "Mark as Resigned",
        "emp_btn_restore": "Restore to Active",
        "emp_confirm_resign": "Confirm resignation? (Employee will lose access and won't appear in payroll)",
        # Navbar & Sidebar
        "nav_home": "Dashboard",
        "nav_monitor": "Monitor",
        "nav_emp": "Employees",
        "nav_leave": "Leave System",
        "nav_settings": "Settings",
        "nav_logout": "Logout",
        "nav_audit_log": "Audit Logs",

        # Monitor Page (Statistics)
        "mon_title": "Employee Statistics Monitor",
        "mon_last_update": "Last Update",
        "mon_total_emp": "Total Employees",
        "mon_present": "Present Today",
        "mon_on_leave": "On Leave Today",
        "mon_pending": "Pending Requests",
        "mon_absent_today": "Absent Today",
        "mon_late_today": "Late Today",
        "mon_early_today": "Early Out Today",
        "mon_chart_monthly": "Leave Statistics (Last 6 Months)",
        "mon_chart_pie": "Leave Type Proportion",
        "mon_attendance_monthly": "Monthly Attendance Overview",
        "mon_pie_normal": "Normal",
        "mon_pie_late": "Late",
        "mon_pie_absent": "Absent",
        "mon_pie_leave": "Leave",
        "mon_chart_unit": "times",
    
        # Leave Types
        "leave_sick": "Sick Leave",
        "leave_personal": "Personal Leave",
        "leave_vacation": "Vacation Leave",

        # PDPA Consent Modal
        "pdpa_title": "Personal Data Protection (PDPA)",
        "pdpa_description": "We prioritize your privacy. Please ensure your data is stored and managed securely in accordance with company policy.",
        "pdpa_purpose_title": "Data Usage Purpose:",
        "pdpa_purpose_1": "Internal human resource management.",
        "pdpa_purpose_2": "Recording attendance and leave history.",
        "pdpa_purpose_3": "Calculating benefits and compensation.",
        "pdpa_dont_show": "I acknowledge and do not show this message again.",
        "pdpa_btn_accept": "Accept and Enter System",

        # Login / Common
        "login_welcome": "Welcome to HRM System",
        "login_btn": "Login",
        "msg_inactive": "Account is inactive. Please contact admin.",
        "msg_expired": "Session expired. Please login again.",
        # Audit Log & System
        "log_title": "Audit Log System",
        "log_subtitle": "Activity History",
        "log_col_time": "Date-Time",
        "log_col_user": "Performer",
        "log_col_action": "Action Type",
        "log_col_details": "Details",
        "log_col_ip": "IP Address",
        "log_no_data": "No data available in table",
        "log_refresh": "Refresh Data",
        "log_search": "Search in Log:",
        "log_info_show": "Showing entries _START_ to _END_ of _TOTAL_ total entries",
        
        # OT Summary Report (English)
        "ot_sum_title": "Overtime (OT) Summary Report",
        "ot_sum_start_date": "Start Date",
        "ot_sum_end_date": "End Date",
        "ot_sum_status": "Status",
        "ot_sum_all": "All",
        "ot_sum_pending": "Pending Approval",
        "ot_sum_approved": "Approved",
        "ot_sum_rejected": "Rejected",
        "ot_sum_search": "Search",
        "ot_sum_header_total": "Total",
        "ot_sum_header_approved": "Approved",
        "ot_sum_header_pending": "Pending",
        "ot_sum_header_rejected": "Rejected",
        "ot_sum_items": "items",
        "ot_sum_hours": "hours",
        "ot_sum_record": "OT Records",
        "ot_sum_no_data": "No data found",
        "ot_sum_period": "in selected period",
        "ot_sum_header_summary": "Summary",
        "ot_sum_total_hours": "Total Hours",
        "ot_sum_by_type": "Summary by OT Type",
        "ot_sum_type_1_0": "OT 1.0x",
        "ot_sum_type_1_5": "OT 1.5x",
        "ot_sum_type_2_0": "OT 2.0x",
        "ot_sum_type_3_0": "OT 3.0x",
        "ot_sum_details_title": "OT Details",
        "ot_sum_export_excel": "Export Excel",
        "ot_sum_col_date": "Date",
        "ot_sum_col_employee": "Employee",
        "ot_sum_col_time": "Time",
        "ot_sum_col_type": "Type",
        "ot_sum_col_minutes": "Minutes",
        "ot_sum_col_hours": "Hours",
        "ot_sum_col_reason": "Reason",
        "ot_sum_col_status": "Status",
        "ot_sum_col_remark": "Remark",
        "ot_sum_badge_approved": "✓ Approved",
        "ot_sum_badge_pending": "⧖ Pending",
        "ot_sum_badge_rejected": "✗ Rejected",
        "ot_sum_empty_remark": "None",
        "ot_sum_no_data_in_period": "No OT data found for selected period",
        "ot_sum_export_no_data": "No data available for export",

        "ot_report_title": "OT Overview Summary",
        "ot_report_minute_unit": "min",
        "ot_report_col_date": "Date",
        "ot_report_col_employee": "Employee",
        "ot_report_col_type": "Type",
        "ot_report_col_minutes": "Minutes",
        "ot_report_col_reason": "Reason",
        
        # Payroll Form (English)
        "pay_subtitle": "Payroll Summary",
        "pay_period_info": "Period",
        "pay_base_salary": "Base Salary (Monthly)",
        "pay_stats": "Stats (Days/Late/Absent)",
        "pay_late_early": "Late/Early Deduction",
        "pay_absent": "Absent Deduction",
        "pay_bonus": "Bonus/Deductions",
        "pay_sso_tax": "SSO / Tax",
        "pay_recalc_new": "Recalculate",
        "pay_recalc_late": "Recalculate Late/Early",
        "pay_clear_draft": "Clear Draft",
        "pay_confirm_clear": "Confirm reset? System will clear draft data and recalculate late/early/absent minutes.",
        "pay_recalc_success": "✅ Late/Early recalculation completed! Click 'Recalculate' to see results.",
        "pay_recalc_error": "❌ Error recalculating data.",
        "pay_error_date_range": "Calculation date differs from standard monthly period",
        "pay_label_late": "Late",
        "pay_label_early": "Early Out",
        "pay_label_absent": "Absent",
        "pay_label_extra": "Add",
        "pay_label_deduct": "Deduct",
        "pay_label_sso": "SSO",
        "pay_label_tax": "TAX",
        "unit_day": "days",
        "unit_min": "min",
        "pay_yellow_note": "Yellow row = Calculation date differs from standard monthly period",
        "pay_save_draft": "Save Draft",
        "pay_finalize": "Confirm Payroll",
        "pay_confirm_finalize": "Confirm payroll for all employees? Staff can immediately view their payslips.",
        "pay_recalc_confirm": "⚠️ Recalculate late and early-out minutes now?\n\nThe system will recalculate based on each employee's current work schedule.",
        "pay_select_dates_first": "Please select a date range first.",
        "pay_csrf_missing": "CSRF token not found. Please refresh the page and try again.",
        
        # Leave Types (English translation mapping)
        "leave_type_sick": "Sick Leave",
        "leave_type_personal": "Personal Leave",
        "leave_type_vacation": "Vacation Leave",
        "leave_type_other": "Other",
        
        # Additional UI elements
        "nav_ot_summary": "OT Summary",
    }
}